### ISSUE TITLE
Correct (newest) versions of all Instructions are not present?

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer.zh-cn#2]
# Module: 00
#### Step: 00

Description of issue

It appears that this repo has versions of the instructions that are older/obsolete.

It is my understanding this new repo is intended to replace the older https://github.com/MicrosoftLearning/AZ-220ZH-Microsoft-Azure-IoT-Developer repo.  However, it appears to have versions of the instructions that are not the newest, and use the older/obsolete method of resource creation using BASH scripts and .azcli files.

On the other hand - the 'old/original' repo (https://github.com/MicrosoftLearning/AZ-220ZH-Microsoft-Azure-IoT-Developer) does appear to contain the latest Instructions using ARM templates for resource deployment.

An example, focused on Lab 05 Instructions, where we see what appears to be the newer ARM-based deployment link listed on top - in the 'old' repo - while on the bottom we see this 'new' repo referencing the older .azcli method:

![image](https://user-images.githubusercontent.com/49700217/153922083-7927ccc7-9826-41a9-a019-9e00e25490ed.png)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by TesterTesterson1004** [comment]
Issue still exists.

**Comment by stonezy123** [comment]
Now, the issue fixed.
https://github.com/MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer.zh-cn/blob/OLPRODLOC/Instructions/Labs/LAB_AK_05-individual-enrollment-of-device-in-dps.md
